# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 22, 19, 24, 29, 123994, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 22, 19, 24, 37, 708204, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
