# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20160722_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='trips',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default=datetime.datetime(2016, 7, 22, 20, 0, 47, 558985, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
